#!/bin/bash

echo -e "\e[32mDownloading Git content from GuilloteauQ/Luky\e[39m"

git clone https://github.com/GuilloteauQ/Luky ~/.Luky


cd ~/.Luky
chmod +x luky
echo "alias luky=\"bash ~/.Luky/luky\"" >> ~/.bashrc
