#!/bin/bash
echo "#!/usr/bin/env python3" > copy_luky.py
echo "import sys
" >> copy_luky.py
echo "import time
" >> copy_luky.py
echo "from subprocess import call
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "# ####################################################
" >> copy_luky.py
echo "# Test Class
" >> copy_luky.py
echo "#
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "class Test:
" >> copy_luky.py
echo "    def __init__(self, function, name, show_time, show_color):
" >> copy_luky.py
echo "        self.function = function
" >> copy_luky.py
echo "        self.name = name
" >> copy_luky.py
echo "        self.result = None
" >> copy_luky.py
echo "        self.show_time = show_time
" >> copy_luky.py
echo "        self.show_color = show_color
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "    def run(self):
" >> copy_luky.py
echo "        try:
" >> copy_luky.py
echo "            self.function()
" >> copy_luky.py
echo "            self.result = True
" >> copy_luky.py
echo "        except:
" >> copy_luky.py
echo "            self.result = False
" >> copy_luky.py
echo "    
" >> copy_luky.py
echo "    def report(self):
" >> copy_luky.py
echo "        time_before = time.time()
" >> copy_luky.py
echo "        self.run()
" >> copy_luky.py
echo "        time_after = time.time()
" >> copy_luky.py
echo "        if self.show_color:
" >> copy_luky.py
echo "            if self.result:
" >> copy_luky.py
echo "                output = \"[\033[32mpassed\033[39m] : {}\".format(self.name)
" >> copy_luky.py
echo "            else:
" >> copy_luky.py
echo "                output = \"[\033[31mfailed\033[39m] : {}\".format(self.name)
" >> copy_luky.py
echo "        else:
" >> copy_luky.py
echo "            if self.result:
" >> copy_luky.py
echo "                output = \"[passed] : {}\".format(self.name)
" >> copy_luky.py
echo "            else:
" >> copy_luky.py
echo "                output = \"[failed] : {}\".format(self.name)
" >> copy_luky.py
echo "        if self.show_time:
" >> copy_luky.py
echo "            output += \" ({} sec)\".format(time_after - time_before)
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "        print(output)
" >> copy_luky.py
echo "        return self.result
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "# ####################################################
" >> copy_luky.py
echo "# Parser Part
" >> copy_luky.py
echo "#
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "def write_header(outfile):
" >> copy_luky.py
echo "    outfile.write(\"#!/usr/bin/env python3.5\n\")
" >> copy_luky.py
echo "    outfile.write(\"from Luky import luky\n\")
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "def write_test_file(path, outfile, show_time, hide_color):
" >> copy_luky.py
echo "    functions_names = get_test_functions_names(path)
" >> copy_luky.py
echo "    line = \"from {} import \".format(path[:-3])
" >> copy_luky.py
echo "    size = len(functions_names)
" >> copy_luky.py
echo "    if size > 0:
" >> copy_luky.py
echo "        for i in range(size - 1):
" >> copy_luky.py
echo "            line += \"{}, \".format(functions_names[i])
" >> copy_luky.py
echo "        line += \"{}\n\".format(functions_names[size - 1])
" >> copy_luky.py
echo "        outfile.write(line)
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "        outfile.write(\"tests_passed = 0\n\")
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "        for function in functions_names:
" >> copy_luky.py
echo "            outfile.write(\"tests_passed += luky.Test({0}, \\\"{0}\\\", {1}, {2}).report()\n\"\
" >> copy_luky.py
echo "                          .format(function, show_time, not hide_color))
" >> copy_luky.py
echo "        outfile.write(\"print(\\\"Tests passed:\\\", tests_passed, \\\"/ {}\\\")\n\".format(size))
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "def get_name(line):
" >> copy_luky.py
echo "    return line[4:-4]
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "def get_test_functions_names(path):
" >> copy_luky.py
echo "    functions_names = []
" >> copy_luky.py
echo "    test_file = open(path, \"r\")
" >> copy_luky.py
echo "    lines = test_file.readlines()
" >> copy_luky.py
echo "    i = 0
" >> copy_luky.py
echo "    while i < len(lines):
" >> copy_luky.py
echo "        if lines[i][:7] == \"#[test]\":
" >> copy_luky.py
echo "            i += 1
" >> copy_luky.py
echo "            while i < len(lines) and lines[i][:3] != \"def\":
" >> copy_luky.py
echo "                i += 1
" >> copy_luky.py
echo "            if i != len(lines) and lines[i][:3] == \"def\":
" >> copy_luky.py
echo "                functions_names.append(get_name(lines[i]))
" >> copy_luky.py
echo "        i += 1
" >> copy_luky.py
echo "    test_file.close()
" >> copy_luky.py
echo "    return functions_names
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "def display_help():
" >> copy_luky.py
echo "    print(\"######################## LUKY ########################\n\")
" >> copy_luky.py
echo "    print(\"Usage:\")
" >> copy_luky.py
echo "    print(\"\t ./luky.py tests_file.py other_tests_file.py\n\")
" >> copy_luky.py
echo "    print(\"Arguments:\")
" >> copy_luky.py
echo "    print(\"-t or --time: Displays the execution time of each test\")
" >> copy_luky.py
echo "    print(\"--no-color: Do not show 'passed' and 'failed' in color\")
" >> copy_luky.py
echo "    print(\"-h or --help: Displays this help\n\n\")
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "def main():
" >> copy_luky.py
echo "    if len(sys.argv) == 1:
" >> copy_luky.py
echo "        print(\"Bad Argument\n\")
" >> copy_luky.py
echo "        display_help()
" >> copy_luky.py
echo "        return
" >> copy_luky.py
echo "    else:
" >> copy_luky.py
echo "        show_time = False
" >> copy_luky.py
echo "        hide_color = False
" >> copy_luky.py
echo "        show_help = False
" >> copy_luky.py
echo "        paths = sys.argv[1:] # We get all the arguments
" >> copy_luky.py
echo "        for path in paths:
" >> copy_luky.py
echo "            # Checking if the files are Python files
" >> copy_luky.py
echo "            if path == \"--time\" or path == \"-t\":
" >> copy_luky.py
echo "                show_time = True
" >> copy_luky.py
echo "            elif path == \"--no-color\":
" >> copy_luky.py
echo "                hide_color = True
" >> copy_luky.py
echo "            elif path == \"-h\" or path == \"--help\":
" >> copy_luky.py
echo "                show_help = True
" >> copy_luky.py
echo "            elif len(path) <= 3 or path[-3:] != \".py\":
" >> copy_luky.py
echo "                print(\"Bad Argument: The file must end by '.py'\")
" >> copy_luky.py
echo "                print(\"Run with -h or --help to see the help\")
" >> copy_luky.py
echo "                return
" >> copy_luky.py
echo "    if show_help:
" >> copy_luky.py
echo "        display_help()
" >> copy_luky.py
echo "    outfile = open(\".out.py\", \"a\")
" >> copy_luky.py
echo "    write_header(outfile)
" >> copy_luky.py
echo "    for path in paths:
" >> copy_luky.py
echo "        if path not in [\"-t\", \"--time\", \"--no-color\", \"-h\", \"--help\"]:
" >> copy_luky.py
echo "            outfile.write(\"print(\\\"---------- {} ----------\\\")\n\".format(path))
" >> copy_luky.py
echo "            write_test_file(path, outfile, show_time, hide_color)
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "    outfile.close()
" >> copy_luky.py
echo "    # Run the file
" >> copy_luky.py
echo "    call([\"python3\", \".out.py\"])
" >> copy_luky.py
echo "    # Delete the file
" >> copy_luky.py
echo "    call([\"rm\", \".out.py\"])
" >> copy_luky.py
echo "    call([\"rm\", \"-rf\", \"__pycache__\"])
" >> copy_luky.py
echo "
" >> copy_luky.py
echo "if __name__ == \"__main__\":
" >> copy_luky.py
echo "    main()
" >> copy_luky.py

python3 copy_luky.py $@

rm copy_luky.py
